### ISSUE TITLE
Allow command line arguments as variables

### ISSUE THREAD

**Issue by maximilianschmitt** [everysquare/pollinate#12]
It's not so nice to be typing JSON and for simple pollinations it would be really nice to pass the arguments CLI-style, e.g.

```
pollinate org/repo -- --name test
```

**Comment by howardroark** [comment]
Totally agree!  Was waiting for someone to ask for this one :p 

I think it would be safe to assume that every 'option' is a part of the `context`... given the simple nature of this tool.  Currently it uses "commander"... I wonder how easy it would be to collect all options and stick them into an object.

**Comment by howardroark** [comment]
@maximilianschmitt This is now done ... https://github.com/everysquare/pollinate/commit/4a29c4e6264253767e8bc1cef6d850ba285fcc94

:)

**Comment by maximilianschmitt** [comment]
awesome work @howardroark , thanks!

**Comment by howardroark** [comment]
:) Question... Would you like the option to omit `template.json` and parse all files with nunjucks by default?  Just passing the data you supply.

**Comment by maximilianschmitt** [comment]
Yes, I think that would make sense. Also, some more ideas/suggestions:
- when omitting `--name`, pollinate creates a directory called `undefined`. I think the git clone behaviour would make more sense: use the repo-name as the folder name, if not specified otherwise
- Take a look at [plop](https://github.com/amwmedia/plop). I think the way you can easily transform the casing of your variable values could make a lot of sense for pollinate
- Maybe delete the `template.json` by default, unless otherwise specified

**Comment by maximilianschmitt** [comment]
I'm really liking where this project is going btw, keep up the great work!

**Comment by howardroark** [comment]
Thanks for the feedback!

I think you should be able to accomplish a lot of what `plop` offers in that sense with [nunjucks filters](https://mozilla.github.io/nunjucks/templating.html#more-filters).  Could add in custom nunjucks filters as well if need be.

That tool makes me think that it would be nice to rsync templates on top of each other if the name already exists (vs an error when a folder name exists).  Maybe require a flag for that or something.

Feel free to submit a pull request for the `undefined` thing ;)

In terms of automatic removal or automatic parsing of all files... I'm thinking it may be best to not make too many assumptions and instead keep it simple so people can be creative with it.
